name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: makeUtil
      working-directory: ./Utilities
      run: make
    - name: make
      working-directory: ./Emulator
      run: make
